paths:
  data_dir: "/data"
  

models:
  text_summary_model: 'llama-3.1-8b-instant'
  image_summary_model: 'llava:13b'
  embedding_model: 'llama3'
  chat_model: 'llama-3.1-70b-versatile'

parameters:
  collection_name: 'multi_modal_rag'


